development:
  adapter: postgresql
  host: localhost
  username: postgresql
  password: eKcGZr59zAa2BEWU
  database: app-d

production:
  adapter: postgresql
  host: ec2-54-225-223-40.compute-1.amazonaws.com
  username: postgresql
  password: eKcGZr59zAa2BEWU
  database: app-p
