development:
  adapter: postgresql
  host: localhost
  username: ubuntu
  password: eKcGZr59zAa2BEWU
  database: app-dev1

production:
  adapter: postgresql
  host: localhost
  username: ubuntu
  password: eKcGZr59zAa2BEWU
  database: app-pro1