development:
  adapter: postgresql
  host:  localhost
  username: tvatgpajcxwtlv
  password:   rl4ehNZhPmCG80HRh6aDHzoTTb
  database: d3tiqsbpu4n17m

production:
  adapter: postgresql
  host: localhost
  username: postgresqladmin
  password: Sama123018120624
  database: UniquelyU
