development:
  adapter: postgresql
  host: localhost
  username: postgresqladmin
  password: Sama123018120624
  database: d3tiqsbpu4n17m

production:
  adapter: postgresql
  host: localhost
  username: postgresqladmin
  password: Sama123018120624
  database: UniquelyU
