development:
  adapter: postgresql
  encoding: utf8
  database: app_development
  pool: 5
  username: ubuntu
  password: eKcGZr59zAa2BEWU

test:
  adapter: postgresql
  encoding: utf8
  database: de9b5q9jac5b2l
  pool: 5
  username: tgvabtrxvekaes
  password: nG34TPYTH4g73DE9XG76-patzG

production:
  adapter: postgresql
  encoding: utf8
  database: de9b5q9jac5b2l
  pool: 5
  username: tgvabtrxvekaes
  password: nG34TPYTH4g73DE9XG76-patzG