development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: eKcGZr59zAa2BEWU
  database: app-dev

production:
  adapter: postgresql
  host: localhost
  username: postgres
  password: eKcGZr59zAa2BEWU
  database: app-productionc