development:
  adapter: postgresql
  host:      ec2-54-225-223-40.compute-1.amazonaws.com
  username: tvatgpajcxwtlv
  password:   rl4ehNZhPmCG80HRh6aDHzoTTb
  database: UniquelyU

production:
  adapter: postgresql
  host: localhost
  username: postgresqladmin
  password: Sama123018120624
  database: UniquelyU
