development:
  adapter: postgresql
  host: localhost
  username: postgresqladmin1
  password: Sama123018120624
  database: UniquelyU

production:
  adapter: postgresql
  host: localhost
  username: postgresqladmin
  password: Sama123018120624
  database: UniquelyU
